### ISSUE TITLE
Undefined control sequence: \prop_get:cn

### ISSUE THREAD

**Issue by westernmagic** [mhelvens/latex-lt3graph#3]
the l3prop interface might have changed, this package no longer works

**Comment by mhelvens** [comment]
Aha. Thanks for letting me know. Indeed, `\prop_get:Nn` seems to have been removed, though it is still mentioned a couple of times in [the documentation](http://mirror.ox.ac.uk/sites/ctan.org/macros/latex/contrib/l3kernel/interface3.pdf). Last time they removed commands, they sent an e-mail to package maintainers.

I'll keep this issue in mind, but I won't have time to fix it this week. For now, replacing every occurrence of `\prop_get:cn` with `\prop_item:cn` should work. If you'd like to test this and then issue a pull request, that would be much appreciated!
